### ISSUE TITLE
You can still win the game if wrong flags have been placed

### ISSUE THREAD

**Issue by hammer065** [derhuerst/cli-minesweeper#1]
If you place more flags than there are mines, its still possible to win the game.
Here an extreme example of it:
https://asciinema.org/a/bqGkvtZjIztnQmpd3cLSgAv5D

**Comment by derhuerst** [comment]
What is the expected behaviour?

**Comment by derhuerst** [comment]
Actually, right now, you win as soon as you have flagged all bombs.

**Comment by hammer065** [comment]
The expected behaviour is, that if you place more flags than there are bombs, that you won't win the game.
Means the player only should place flags on top of bombs and not on empty fields.

**Comment by derhuerst** [comment]
Sounds reasonable. 😛 Would you mind making a PR?

**Comment by LRFLEW** [comment]
For the record, the Minesweeper game included in Windows set the win condition to be when all of the **non-mine** locations have been revealed. You can set flags on all of the mines exactly, but it doesn't count as a win until all of the other spaces have been revealed.

**Comment by derhuerst** [comment]
Okay, so the correct win condition would be "all bombs flagged and all empty spaces revealed". @LRFLEW Thanks for the PR!
